package EmployeeDao;

import Entities.Employee;
import Exceptions.EmployeeException;

public interface EmployeeDao {

	public boolean registerEmployee(Employee employee)throws EmployeeException;
	// the above method take an Employee object without an empId and returned the
	//registered Employee object having the autogenerated Id
	public Employee getEmployeeById(int empId)throws EmployeeException;
	public boolean deleteEmployeeById(int empId) throws EmployeeException;
	public boolean updateEmployee(Employee employee)throws EmployeeException;
	//the above method will return the updated Employee object, if we supply any Employee
//	object, which is not existing then it should throw the EmployeeException

}
